# Exeter site
all:
  children:
    enterprise_exeter:          
      hosts:
        ent-exe-rt-ce-1: { ansible_host: 192.168.110.10 }
        ent-exe-rt-ce-2: { ansible_host: 192.168.110.11 }
        isp2-exe-rt-pe-1: { ansible_host: 192.168.110.20}
        isp2-exe-rt-pe-2: { ansible_host: 192.168.110.21}