# Exeter customer edge router 1: circuit A to ISP2
loopback: 10.0.8.2
interfaces:
  - { name: Ethernet1, description: Exeter PE RT1 P2P, ip: 10.30.0.1/31 }
  - { name: Ethernet3, description: Exeter CE Peering, ip: 10.100.0.5/31 }
